### ISSUE TITLE
does not work on rtw8852be

### ISSUE THREAD

**Issue by saikatm** [lwfinger/rtw89#168] opened 2022-10-15 17:21 UTC
distro: fedora 36
kernel: 5.19.15.201

Issue: wifi missing 

1. I was using [rtw8852be](https://github.com/lwfinger/rtw8852be) repo
2. updated the kernel to latest
3. rebooted wifi gone
4. compiled this rtw89 repo
5. did make sudo install
6. did cold reboot

wifi is still missing!
I dont know how to provide logs and other stuff. let me know how I can provide more details. thank you so much.

**Comment by AJRepo** [comment] 2022-10-27 13:42
This may be a duplicate of #172 , an issue which has been solved. 

See that ticket for the logs and commands executed for diagnosis.

**Comment by henk717** [comment] 2022-11-30 08:00
Having this on my HP Elitebook 865 G9 with latest firmware.
[  197.111228] rtw89_8852be 0000:01:00.0: Direct firmware load for rtw89/rtw8852b_fw.bin failed with error -2
[  197.111234] rtw89_8852be 0000:01:00.0: failed to early request firmware: -2
[  197.111346] rtw89_8852be 0000:01:00.0: enabling device (0000 -> 0003)
[  197.111403] rtw89_8852be 0000:01:00.0: Direct firmware load for rtw89/rtw8852b_fw.bin failed with error -2
[  197.111407] rtw89_8852be 0000:01:00.0: failed to request firmware
[  197.113388] rtw89_8852be 0000:01:00.0: failed to wait firmware completion
[  197.113393] rtw89_8852be 0000:01:00.0: failed to setup chip information

**Comment by lwfinger** [comment] 2022-11-30 15:07
'sudo apt install *firmware-realtek' should fix you up.  If that does not work, download https://lwfinger.com/download/rtw8852b_fw.bin and copy the bin file (as root) to directory /lib/firmware/rtw89/.

**Comment by Guite** [comment] 2022-12-09 17:30
Copying the bin file fixed this issue for me. Thanks for this hint and your entire efforts @lwfinger

**Comment by lwfinger** [comment] 2022-12-09 18:50
I knew that would do it. You should also post on your distro's site asking them to update their firmware package.

**Closed by lwfinger** 2022-12-09 18:50 UTC
